version: '3.9'

services:
  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama-init
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: []
    command: 
     - /bin/sh 
     - -c 
     - ollama pull mistral && ollama pull avr/sfr-embedding-mistral
    volumes:
      - ollama_data:/root/.ollama
    depends_on:
      ollama:
        condition: service_started
    networks:
      - backend
    
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - MODELS=mistral:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      backend:
        aliases:
          - ollama

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend


volumes:
  ollama_data:
  qdrant_data:

networks:
  backend: