version: '3.9'

services:
  some-machine-learning:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - DB_HOST=qdrant
      - CONTENT_BACKEND=minio
      - CONTENT_MINIO_ENDPOINT=minio:9000
      - CONTENT_MINIO_ACCESSKEY=minio
      - CONTENT_MINIO_SECRETKEY=minio123
      - MEMORY_BACKEND=redis
      - MEMORY_REDIS_HOST=redis
      - MEMORY_REDIS_PORT=6379
      # - LLMMODEL_CHAT="mistral"
      - LLMMODEL_CHAT=hf.co/alirionx/mistral-gguf-dq
    networks:
      backend:
        aliases:
          - some-machine-learning

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - MODELS=mistral:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      backend:
        aliases:
          - ollama
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      backend:
        aliases:
          - qdrant

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    networks:
      backend:
        aliases:
          - minio

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      backend:
        aliases:
          - redis
  
volumes:
  ollama_data:
  qdrant_data:
  minio_data:
  redis_data:


networks:
  backend: